#! /bin/sh

. /etc/init.d/functions

export JAVA_HOME=/usr/java/jdk1.7.0_75
     
PF_DIR=/opt/pingfederate-7.3.0
PF_USER=pingfed
 
SBIN_DIR=$PF_DIR/pingfederate/sbin 
SERVICE="PingFederate" 
LOCKFILE=/var/lock/subsys/pingfederate

start() {
        echo -n "Starting $SERVICE: "
        su $PF_USER -c $SBIN_DIR/pingfederate-run.sh && success || failure
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $LOCKFILE
	echo
        return $RETVAL
}

stop() {
        echo -n "Shutting down $SERVICE: "
        su $PF_USER -c $SBIN_DIR/pingfederate-shutdown.sh && success || failure
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
        echo
        return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit $?
